Repository dataforgoodfr/offseason_ogre, pull requests merged in 2022-01, with the labels that each got.

#8 added sequelize model PlaneConsumption
  server/OLD_create_db.sql
  server/app/OGREConstants.js
  server/app/controllers/playerController.js
  server/app/models/PlaneConsumption.js
  server/app/models/index.js
  server/migrate_seed_db_with_sequelize.js
Labels: enhancement

#9 Features/#5 archi tests
  README.md
  server/.sequelizerc
  server/Dockerfile
  server/app/config/config.js
  server/app/controllers/playerController.js
  server/app/db/migrations/20220107190301-ogre.js
  server/app/db/models/CarConsumption.js
  server/app/db/models/PlaneConsumption.js
  server/app/db/models/Player.js
  server/app/db/models/index.js
  server/app/db/seed/20220107190459-ogre.js
  server/app/models.test/CarConfiguration.test.js
  server/app/tests/models/CarConsumption.test.js
  server/app/tests/models/Player.test.js
  server/app/tests/routes/router.test.js
  server/index.js
  server/jest.config.js
  server/migrate_seed_db_with_sequelize.js
  server/package.json
  server/run.sh
Labels: unit tests

#19 Feature/#3 windturbineonshore model
  server/app/OGREConstants.js
  server/app/controllers/playerController.js
  server/app/controllers/windTurbineOnshoreProductionController.js
  server/app/db/migrations/20220107190301-ogre.js
  server/app/db/models/WindTurbineOnshoreProduction.js
  server/app/db/seed/20220107190459-ogre.js
  server/app/router.js
Labels: enhancement

#17 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
